Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Arthur Henrique Kronbauer 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/03/2026
Var
// Seção de Declarações das variáveis 
   idade : inteiro
   peso : real
   altura : real
   mediaIdade: real
   percOlhosAzuis : real
   corOlhos : caractere
   opcao : caractere
   somaIdade : inteiro
   qtdRuivos: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   mediaIdade <- 0
   somaIdade <- 0
   opcao <- "1"
   
   enquanto opcao <> "2" faca

   fimenquanto

Fimalgoritmo